# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "miniconda-latest"
  commands:
    - conda env create -f contributor_environment.yml
    - conda run -n PLASMAG_contrib python --version
    - conda run -n PLASMAG_contrib sphinx-build -b html docs "$READTHEDOCS_OUTPUT/html"

sphinx:
  configuration: docs/conf.py
